version: "3.9"


services:
  backend:
    build: ./backend
    command: ["/backend/docker/app.sh"]
    ports:
    - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    depends_on:
      - dbhack

  frontend:
    build: ./frontend
    ports:
    - "5173:5173"
    volumes:
    - ./frontend:/user/src/app
    depends_on:
    - backend

  pgadminhack:
    image: dpage/pgadmin4:latest
    env_file:
      - ./backend/.env
    ports:
      - "8085:80"
    depends_on:
    - dbhack


  dbhack:
    image: postgres:15
    container_name: dbhack
    command: -p 1221
    expose:
        - 1221
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

volumes:
  postgres_data:
  client:
  server: