"""TrainDate

Revision ID: 84898312508e
Revises: e3e3b99b7b81
Create Date: 2023-11-11 05:03:10.982207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84898312508e'
down_revision = 'e3e3b99b7b81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_index', sa.String(), nullable=True),
    sa.Column('station_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wagon_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_train_data'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_data')
    # ### end Alembic commands ###
